"use client";

import { formatHumanReadableDate } from "@/lib/utils";

export function WaybillPrintView({ delivery }: { delivery: any }) {
  const recipientName = delivery.customer ? delivery.customer.name : delivery.station ? delivery.station.name : "Unknown";
  const date = new Date(delivery.createdAt);

  return (
    <div className="p-8 bg-white text-black text-sm w-full max-w-4xl mx-auto min-h-screen">
      <div className="flex justify-between items-start mb-8 border-b-2 border-black pb-4">
        <div>
          <h1 className="text-3xl font-black uppercase tracking-widest">WAYBILL / DELIVERY NOTE</h1>
          <p className="text-gray-600 font-medium mt-1">Ref: {delivery.transport?.order?.reference || "N/A"}</p>
        </div>
        <div className="text-right">
          <p className="font-bold">Date: {formatHumanReadableDate(date)}</p>
          <p>Destination: {recipientName}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8 mb-8">
        <div>
          <h3 className="font-bold uppercase border-b border-black mb-2 pb-1">Delivery Details</h3>
          <p><strong>To:</strong> {recipientName}</p>
          <p><strong>Address:</strong> {delivery.customer?.address || delivery.station?.location || "N/A"}</p>
          <p><strong>Product:</strong> {delivery.transport?.order?.productType || "PMS"}</p>
          <p><strong>Volume Despatched:</strong> {Number(delivery.litersDespatched).toLocaleString()} Liters</p>
        </div>
        <div>
          <h3 className="font-bold uppercase border-b border-black mb-2 pb-1">Transport Details</h3>
          <p><strong>Transporter:</strong> {delivery.transport?.transporter?.name || "N/A"}</p>
          <p><strong>Truck Plate No:</strong> {delivery.transport?.truck?.plateNumber || "N/A"}</p>
          <p><strong>Driver Name:</strong> {delivery.transport?.driver?.firstName ? `${delivery.transport.driver.firstName} ${delivery.transport.driver.lastName}` : "N/A"}</p>
          <p><strong>Source Depot:</strong> {delivery.transport?.order?.sourceDepot || "N/A"}</p>
        </div>
      </div>

      <div className="mt-12 space-y-8">
        <div className="flex justify-between mt-16 pt-8 border-t border-gray-300">
          <div className="text-center w-48">
            <div className="border-b border-black h-8 mb-2"></div>
            <p className="font-bold">Driver Signature</p>
          </div>
          <div className="text-center w-48">
            <div className="border-b border-black h-8 mb-2"></div>
            <p className="font-bold">Receiver Signature</p>
            <p className="text-xs text-gray-500 mt-1">Confirming received volume</p>
          </div>
        </div>
      </div>
      
      <div className="mt-12 text-center text-xs text-gray-500">
        <p>Generated by Fuel Management System</p>
      </div>
    </div>
  );
}
